import Dropdown from "./Dropdown";
import Toggle from "./Toggle";
import Menu from "./Menu";
import Item from "./Item";
import Line from "./Line";
Dropdown.Trigger = Toggle;
Dropdown.Menu = Menu;
Dropdown.Item = Item;
Dropdown.line=Line;
export default Dropdown;
